apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: ott
build:
  artifacts:
    #
    #   Database images
    #
    - image: loaded-pg
      context: docker/postgres
      docker:
        dockerfile: Dockerfile
    - image: migration-pg
      context: .
      docker:
        dockerfile: docker/postgres/migration.Dockerfile
        buildArgs:
          CRATE_NAME: "ott-db-migration"

    #
    #   CONNECTORS 
    #
    - image: posts-connector
      context: connectors
      docker:
        dockerfile: Dockerfile
        buildArgs:
          CONFIG_FILE: "posts-config.yaml"
    - image: likes-connector
      context: connectors
      docker:
        dockerfile: Dockerfile
        buildArgs:
          CONFIG_FILE: "likes-config.yaml"


    #
    # The actual main services
    #
    - image: ott-embed
      context: .
      docker:
        dockerfile: docker/rust-service/Dockerfile
        buildArgs:
          CRATE_NAME: "ott-embed"
    - image: ott-filter
      context: .
      docker:
        dockerfile: docker/rust-service/Dockerfile
        buildArgs:
          CRATE_NAME: "ott-filter"
    - image: ott-xrpc
      context: .
      docker:
        dockerfile: docker/rust-service/Dockerfile
        buildArgs:
          CRATE_NAME: "ott-xrpc"


  tagPolicy:
    envTemplate:
      template: >-
        {{- if contains "loaded-pg" .IMAGE_NAME -}}
          {{.POSTGRES_VERSION | default "17"}}
        {{- else -}}
          {{.GIT_COMMIT | default "HEJA"}}
        {{- end -}}
deploy:
  helm:
    hooks:
      before:
        - host:
            command: ["sh", "-c", "./hooks.sh"]
    releases:
      - name: system-setup
        chartPath: helm/system-setup
        valuesFiles:
          - helm/system-setup/values.yaml
        version: 0.1.0
        wait: true

      - name: ott
        chartPath: helm/ott
        valuesFiles:
          - helm/ott/values.yaml
        setValueTemplates:
          cloudflared.token: "{{.CLOUDFLARE_TUNNEL_TOKEN}}"
          postgresql.migration_image_fqn: "{{.IMAGE_FULLY_QUALIFIED_migration_pg}}"
          services[0].image.fqn: "{{.IMAGE_FULLY_QUALIFIED_likes_connector}}"
          services[1].image.fqn: "{{.IMAGE_FULLY_QUALIFIED_posts_connector}}"
          services[2].image.fqn: "{{.IMAGE_FULLY_QUALIFIED_ott_filter}}"
          services[3].image.fqn: "{{.IMAGE_FULLY_QUALIFIED_ott_embed}}"
          services[4].image.fqn: "{{.IMAGE_FULLY_QUALIFIED_ott_xrpc}}"
        version: 0.1.0
