apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 1
  imageName: {{ .Values.postgresql.imageName }}
  storage:
    size: 10Gi
  enableSuperuserAccess: true
  postgresql:
    shared_preload_libraries:
      - pg_cron
