{{- range $name, $service := .Values.services }}
{{- $serviceName := $name | replace "_" "-" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceName }}
  labels:
    app: {{ $serviceName }}
spec:
  replicas: {{ $service.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ $serviceName }}
  template:
    metadata:
      labels:
        app: {{ $serviceName }}
    spec:
      containers:
      - name: connector
        image: "{{ $service.image.fqn }}"
        imagePullPolicy: {{ $service.image.pullPolicy }}
        env:
        {{- toYaml $service.env | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  labels:
    app: {{ $serviceName }}
spec:
  selector:
    app: {{ $serviceName }}
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
{{- end }}
