postgresql:
  imageName: loaded-pg:17

deployments:
  - name: likes-connector
    image:
      fqn: likes-connector
      pullPolicy: IfNotPresent
    replicas: 1

  - name: posts-connector
    image:
      fqn: posts-connector
      pullPolicy: IfNotPresent
    replicas: 1

  - name: ott-filter
    image:
      fqn: ott-filter
      pullPolicy: IfNotPresent
    replicas: 1

  - name: ott-embed
    image:
      fqn: ott-embed
      pullPolicy: IfNotPresent
    env:
    - name: DATABASE_USER
      valueFrom:
        secretKeyRef:
          name: postgres-app
          key: username
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-app
          key: password
    - name: DATABASE_URL
      value: "postgres://$(DATABASE_USER):$(DATABASE_PASSWORD)@postgres-rw.default.svc.cluster.local:5432"

  - name: ott-xrpc
    image:
      fqn: ott-embed
      pullPolicy: IfNotPresent
    replicas: 1
    replicas: 1
    env:
    - name: EXTERNAL_BASE
      value: localhost 
