postgresql:
  imageName: loaded-pg:17

deployments:
  - name: likes-connector
    image:
      fqn: likes-connector
      pullPolicy: IfNotPresent
    replicas: 1

  - name: posts-connector
    image:
      fqn: posts-connector
      pullPolicy: IfNotPresent
    replicas: 1

  - name: ott-filter
    image:
      fqn: ott-filter
      pullPolicy: IfNotPresent
    replicas: 1

  - name: ott-embed
    image:
      fqn: ott-embed
      pullPolicy: IfNotPresent

  - name: ott-xrpc
    image:
      fqn: ott-embed
      pullPolicy: IfNotPresent
    replicas: 1
    replicas: 1
