postgresql:
  imageName: loaded-pg:17
  migration_image_fqn: migration-pg:17

cloudflared:
  enabled: true
  token: {}

app_auth:
  did: {}
  key: {}

services:
  likes_connector:
    image:
      fqn: likes-connector
      pullPolicy: IfNotPresent
    replicas: 1

  posts_connector:
    image:
      fqn: posts-connector
      pullPolicy: IfNotPresent
    replicas: 1

  ott_filter:
    image:
      fqn: ott-filter
      pullPolicy: IfNotPresent
    replicas: 1

  ott_embed:
    image:
      fqn: ott-embed
      pullPolicy: IfNotPresent
    env:
    - name: DATABASE_USER
      valueFrom:
        secretKeyRef:
          name: postgres-app
          key: username
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-app
          key: password
    - name: DATABASE_URL
      value: "postgres://$(DATABASE_USER):$(DATABASE_PASSWORD)@postgres-rw.default.svc.cluster.local:5432/app"

  ott_xrpc:
    image:
      fqn: ott-embed
      pullPolicy: IfNotPresent
    replicas: 1
    replicas: 1
    env:
    - name: EXTERNAL_BASE
      value: localhost 
    - name: APP_DID
      valueFrom:
        secretKeyRef:
          name: app-auth
          key: did
    - name: APP_KEY
      valueFrom:
        secretKeyRef:
          name: app-auth
          key: KEY
