apiVersion: 0.1.0
meta:
  version: x.y.z
  name: likes-connector
  type: http-source
  topic: raw-likes
  producer:
    batch-size: "4 MB"
http:
  endpoint: "wss://jetstream2.us-east.bsky.network/subscribe?wantedCollections=app.bsky.feed.like"
