apiVersion: 0.1.0
meta:
  version: x.y.z
  name: posts-connector
  type: http-source
  topic: raw-posts
  producer:
    batch-size: "4 MB"
http:
  endpoint: "wss://jetstream2.us-east.bsky.network/subscribe?wantedCollections=app.bsky.feed.post"
transforms:
  - uses: aleeve/contruct-post-uri@0.1.0
  - uses: aleeve/assign-record-key@0.1.0
    with:
      key: uri
